#Use a fallback rendertype for certain objects that normally use custom core shaders. Improves compatibility with shader mods but might not look as good.
render_fallback = false
#The amount of millibuckets one nugget is worth when molten, only affects fluid tooltips.
nugget_fluid_value = 10

